# Generated by Django 5.0 on 2023-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=500)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sent_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('demo_url', models.URLField()),
                ('github_url', models.URLField()),
                ('image', models.ImageField(upload_to='images')),
                ('delay', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('visible', models.CharField(choices=[('ON', 'Visible'), ('OFF', 'Unvisible')], default='ON', max_length=3)),
            ],
        ),
    ]
